### ISSUE TITLE
Not able to run tests 

### ISSUE THREAD

**Issue by SuryaEnjarapu** [sivaprasadreddy/spring-modular-monolith#6]
Hi Siva,

I ma not able run tests individually (module) or using mvn not sure if i missing any thing.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'flyway' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsatisfied dependency expressed through method 'flyway' parameter 0: Error creating bean with name 'flywayContainerConnectionDetailsForPostgresContainer': Error creating bean with name 'postgresContainer' defined in com.sivalabs.bookstore.TestcontainersConfiguration: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325) ~[spring-beans-6.2.0-M7.jar:6.2.0-M7]

Errors: 
[ERROR]   BookStoreApplicationTests.contextLoads » IllegalState Failed to load ApplicationContext for [WebMergedContextConfiguration@6a40a370 testClass = com.sivalabs.bookstore.BookStoreApplicationTests, locations = [], classes = [com.sivalabs.bookstore.BookStoreApplication, com.sivalabs.bookstore.TestcontainersConfiguration], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@2a7ed1f, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@5 ....
[INFO] 
[ERROR] Tests run: 6, Failures: 0, Errors: 4, Skipped: 0

**Comment by sivaprasadreddy** [comment]
From the error stacktrace:

"Previous attempts to find a Docker environment failed."

This means Docker is not running on your system. The tests are using Testcontainers which need Docker to be running.
